### ISSUE TITLE
Set up LSVD gateway servers for use with ESI

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/lsvd-rbd#21]
Using the same 5 D4N nodes with NVMe drives, connected to the Ceph research cluster.

**Comment by joachimweyl** [comment]
does this issue fit in [this epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTExNDEx)?

**Comment by knikolla** [comment]
> does this issue fit in [this epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTExNDEx)?

@joachimweyl Don't know. I don't have enough context for that epic and I don't see any issues associated to it.

**Comment by knikolla** [comment]
Closing this issue for now. We have a gateway up for experiments.
